version: '3.0'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      app-stack:
        aliases:
          - docker.mysql.db

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: --requirepass 123456 --appendonly yes
    networks:
      app-stack:
        aliases:
          - docker.redis.db

  nacos:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - 8848:8848
    networks:
      - app-stack

networks:
  app-stack:
    external: true

